import Link from 'next/link';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Top navigation */}
        <nav className="bg-gray-800 text-white p-2 flex space-x-4">
          <Link href="/" className="hover:underline">Home</Link>
          <Link href="/laboratory" className="hover:underline">Laboratory</Link>
        </nav>
        {/* Main content */}
        <main className="flex-1 container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
